import type { CSSProperties } from "react";

type Styles = Record<string, CSSProperties>;

export const S: Styles = {
  container: {
    maxWidth: 440,
    margin: "0 auto",
    padding: "12px 16px 24px",
    minHeight: "100vh",
    boxSizing: "border-box",
    fontFamily: "'Noto Sans JP', 'Hiragino Sans', sans-serif",
    background: "linear-gradient(175deg, #FAF7F1 0%, #F0EBE0 50%, #E8E0CF 100%)",
  },
  loadingWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "80vh",
  },

  heroSection: { textAlign: "center", padding: "28px 0 20px" },
  heroIcon: { fontSize: 44, filter: "drop-shadow(0 2px 4px rgba(0,0,0,0.1))" },
  heroTitle: { fontSize: 34, fontWeight: 800, color: "#3A3228", margin: "2px 0", letterSpacing: -1 },
  heroSub: { fontSize: 13, color: "#8B7E6A", letterSpacing: 3, margin: 0 },

  sectionTitle: { fontSize: 14, fontWeight: 700, color: "#6B5F4F", margin: "0 0 10px", letterSpacing: 1 },

  tripCard: {
    display: "block",
    width: "100%",
    textAlign: "left",
    padding: "14px 16px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.8)",
    border: "1px solid rgba(212,201,181,0.5)",
    boxShadow: "0 2px 8px rgba(58,50,40,0.06)",
    cursor: "pointer",
    fontFamily: "inherit",
    WebkitTapHighlightColor: "transparent",
  },
  tripCardName: { fontSize: 16, fontWeight: 700, color: "#3A3228" },
  tripCardMeta: { fontSize: 12, color: "#8B7E6A", marginTop: 2 },
  tripCardAmount: { fontSize: 18, fontWeight: 800, color: "#3A3228" },

  card: {
    background: "rgba(255,255,255,0.75)",
    backdropFilter: "blur(8px)",
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
    border: "1px solid rgba(212,201,181,0.5)",
    boxShadow: "0 2px 10px rgba(58,50,40,0.05)",
  },
  cardTitle: { fontSize: 15, fontWeight: 700, color: "#3A3228", margin: "0 0 12px" },

  label: { display: "block", fontSize: 12, fontWeight: 600, color: "#6B5F4F", marginBottom: 6 },
  input: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 10,
    border: "2px solid #D4C9B5",
    background: "#FDFBF7",
    fontSize: 15,
    color: "#3A3228",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
  },
  select: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 10,
    border: "2px solid #D4C9B5",
    background: "#FDFBF7",
    fontSize: 15,
    color: "#3A3228",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
    cursor: "pointer",
  },
  hint: { fontSize: 12, color: "#8B7E6A", marginTop: 6, marginBottom: 0, fontStyle: "italic" },

  primaryBtn: {
    width: "100%",
    padding: "14px 0",
    borderRadius: 14,
    border: "none",
    background: "linear-gradient(135deg, #5A4E3E, #7B6E5A)",
    color: "#FDFBF7",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    boxShadow: "0 4px 16px rgba(58,50,40,0.2)",
    letterSpacing: 1,
  },
  dashedBtn: {
    width: "100%",
    padding: "8px 0",
    borderRadius: 10,
    border: "2px dashed #C4B9A5",
    background: "transparent",
    color: "#8B7E6A",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  createTripBtn: {
    width: "100%",
    padding: "18px 16px",
    borderRadius: 16,
    border: "2px dashed #B5AA96",
    background: "rgba(255,255,255,0.4)",
    color: "#6B5F4F",
    cursor: "pointer",
    fontFamily: "inherit",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    fontSize: 14,
    fontWeight: 600,
  },
  iconBtn: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: "none",
    background: "#E8E0CF",
    color: "#8B7E6A",
    cursor: "pointer",
    fontSize: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  topBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    padding: "6px 0",
  },
  topTitle: { fontSize: 16, fontWeight: 700, color: "#3A3228" },
  navBtn: {
    background: "none",
    border: "none",
    color: "#6B5F4F",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    padding: "6px 0",
  },

  exportBtn: {
    padding: "6px 14px",
    borderRadius: 10,
    border: "1px solid #C4B9A5",
    background: "#FDFBF7",
    color: "#6B5F4F",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },

  liveSettlement: {
    padding: "16px 18px",
    borderRadius: 16,
    background: "linear-gradient(135deg, #3A3228, #5A4E3E)",
    boxShadow: "0 4px 20px rgba(58,50,40,0.25)",
    marginBottom: 14,
  },
  liveTransfer: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "7px 10px",
    background: "rgba(255,255,255,0.1)",
    borderRadius: 10,
    color: "#FDFBF7",
    fontSize: 13,
  },

  memberRow: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    paddingBottom: 4,
    marginBottom: 14,
  },
  memberCard: {
    flex: "0 0 auto",
    padding: "10px 8px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.75)",
    border: "1px solid rgba(212,201,181,0.4)",
    textAlign: "center",
    cursor: "pointer",
    fontFamily: "inherit",
    minWidth: 72,
    WebkitTapHighlightColor: "transparent",
  },

  avatarTiny: {
    width: 24,
    height: 24,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontSize: 11,
    fontWeight: 700,
  },
  avatarSm: {
    width: 30,
    height: 30,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontSize: 13,
    fontWeight: 700,
  },
  avatarMd: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontSize: 15,
    fontWeight: 700,
  },
  avatarLg: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontSize: 24,
    fontWeight: 700,
  },

  expCard: {
    padding: "12px 14px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.75)",
    border: "1px solid rgba(212,201,181,0.4)",
  },
  expListItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 0",
    borderBottom: "1px solid #EDE6D8",
  },
  tinyBtn: {
    background: "none",
    border: "none",
    color: "#6B5F4F",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    padding: "4px 6px",
  },

  chipRow: { display: "flex", flexWrap: "wrap", gap: 6 },
  chipOff: {
    padding: "6px 14px",
    borderRadius: 20,
    border: "2px solid #D4C9B5",
    background: "#FDFBF7",
    color: "#6B5F4F",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  chipOn: {
    padding: "6px 14px",
    borderRadius: 20,
    border: "2px solid #6B5F4F",
    background: "#6B5F4F",
    color: "#FDFBF7",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  currencyToggle: {
    display: "flex",
    borderRadius: 10,
    overflow: "hidden",
    border: "2px solid #D4C9B5",
    flexShrink: 0,
  },
  curBtnOff: {
    padding: "8px 14px",
    border: "none",
    background: "#FDFBF7",
    color: "#6B5F4F",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  curBtnOn: {
    padding: "8px 14px",
    border: "none",
    background: "#6B5F4F",
    color: "#FDFBF7",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },

  statBox: {
    flex: 1,
    padding: "14px 16px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.75)",
    border: "1px solid rgba(212,201,181,0.4)",
    textAlign: "center",
  },
  statLabel: { fontSize: 11, fontWeight: 600, color: "#8B7E6A", letterSpacing: 1, marginBottom: 4 },
  statValue: { fontSize: 20, fontWeight: 800, color: "#3A3228" },

  transferRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 0",
    borderBottom: "1px solid #EDE6D8",
  },

  barBg: { width: "100%", height: 6, borderRadius: 3, background: "#EDE6D8", overflow: "hidden" },
  barFill: { height: "100%", borderRadius: 3 },

  emptyBlock: { textAlign: "center", padding: "36px 16px" },

  fab: {
    position: "fixed",
    bottom: 20,
    left: "50%",
    transform: "translateX(-50%)",
    padding: "13px 28px",
    borderRadius: 50,
    border: "none",
    background: "linear-gradient(135deg, #5A4E3E, #7B6E5A)",
    color: "#FDFBF7",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    boxShadow: "0 6px 24px rgba(58,50,40,0.3)",
    zIndex: 100,
    whiteSpace: "nowrap",
  },
};
